#!/data/data/com.termux/files/usr/bin/bash

INPUT="$1"

if [ -z "$INPUT" ]; then
    echo "Usage: bash speak.sh filename.txt"
    exit 1
fi

OUTPUT="${INPUT%.*}.mp3"

echo "Choose language:"
echo "1. English"
echo "2. Hindi"
echo "3. Urdu"
echo "4. Hinglish"

read -p "Enter choice: " CHOICE

case "$CHOICE" in
    1)
        VOICE="en-IN-PrabhatNeural"
        ;;
    2)
        VOICE="hi-IN-SwaraNeural"
        ;;
    3)
        VOICE="ur-PK-UzmaNeural"
        ;;
    4)
        VOICE="hi-IN-SwaraNeural"
        ;;
    *)
        echo "Invalid choice."
        exit 1
        ;;
esac

edge-tts \
--voice "$VOICE" \
--rate=-10% \
--file "$INPUT" \
--write-media "$OUTPUT"

echo ""
echo "Done: $OUTPUT"
